"""Measure how much a note-number pivot costs, using the eleven reference .iom files.

Usage:  python -m tools.iom.analyze data/legacy-iom > docs/evidence/note-number-pivot-loss.md

An .iom note table maps `foreign note -> host internal note`. The host layout is the pivot,
and it is a MIDI note number, so the pivot has at most 128 slots. Wherever two source notes
share a target, one distinction is gone and inversion cannot recover it. This script counts
exactly that. It is the evidence behind ADR-0001.
"""

import pathlib
import sys

from .iom import IOMap


def load(root: pathlib.Path) -> dict[str, IOMap]:
    return {p.stem: IOMap.read(p) for p in sorted(root.glob("*.iom"))}


def report(maps: dict[str, IOMap]) -> str:
    out: list[str] = []
    w = out.append
    w("# Evidence: the cost of a note-number pivot\n")
    w("Generated by `python -m tools.iom.analyze data/legacy-iom`. Do not edit by hand.\n")
    w("Each `.iom` file maps a foreign layout onto the host's internal layout. That internal")
    w("layout is the pivot, and it is a MIDI note number. Where two source notes share one")
    w("target, a distinction is destroyed on the way in and no inversion can recover it.\n")

    rows = []
    for name, m in maps.items():
        mapped = [v[0] for v in m.notes.values() if v]
        rows.append((name, len(mapped), len(set(mapped))))
    rows.sort(key=lambda r: (r[2] - r[1], r[0]))

    w("| Layout | source notes mapped | distinct pivot slots hit | distinctions lost | loss |")
    w("|---|---:|---:|---:|---:|")
    tot_src = tot_dst = 0
    for name, src, dst in rows:
        tot_src += src
        tot_dst += dst
        w(f"| {name} | {src} | {dst} | {src - dst} | {100 * (src - dst) / src:.0f} % |")
    w(f"\nAcross all {len(rows)} layouts: {tot_src} mapped source notes collapse onto")
    w(f"{tot_dst} distinct pivot slots.\n")

    worst = min(rows, key=lambda r: r[2] - r[1])[0]
    w(f"## Worst case: {worst}\n")
    w("| pivot slot | source notes collapsing into it |")
    w("|---:|---|")
    for target, sources in sorted(
        maps[worst].collisions().items(), key=lambda kv: (-len(kv[1]), kv[0])
    )[:12]:
        w(f"| {target} | {', '.join(map(str, sources))} ({len(sources)}) |")
    w("")
    w("## Controller table\n")
    ident = [n for n, m in maps.items() if all(m.ccs.get(k) == [k] for k in range(128))]
    w(f"{len(ident)} of {len(maps)} files carry a pure identity controller table, so the")
    w("controller half of the format is informationally empty. Hi-hat pedal CC is not")
    w("addressed by any of them.\n")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    root = pathlib.Path(argv[1] if len(argv) > 1 else "data/legacy-iom")
    maps = load(root)
    if not maps:
        print(f"no .iom files under {root}", file=sys.stderr)
        return 1
    sys.stdout.write(report(maps))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
